[build-system]
requires = ['setuptools', 'cython <3, >=0.21']
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = [
  "apt-get update && apt-get install --yes wget",
  "mkdir -p ~/miniconda3",
  "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh",
  "bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3",
  "rm -rf ~/miniconda3/miniconda.sh",
  "~/miniconda3/bin/conda init bash",
  "conda create -n scipwheel",
  "conda activate scipwheel",
  "conda install -y -c conda-forge scip",
]
environment = {LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH", SCIPOPTDIR="$CONDA_PREFIX"}
build-frontend = "build"
# OneTBB, as of version 2021.8.0, does not build on manylinux2014 - https://github.com/oneapi-src/oneTBB/issues/950
# And manylinux_2_24 is EOL - https://github.com/pypa/manylinux#docker-images
manylinux-x86_64-image = "manylinux_2_28"
# There is no manylinux_2_28 for i686
# Until we have alpine - https://github.com/sagemath/sage/issues/33083
skip = "*-musllinux*"
