name: Integration test

env:
  version: 8.0.0

# runs on branches and pull requests; doesn't run on tags.
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:

  Integration-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare python environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel cython networkx pytest-cov

      - name: Install PySCIPOpt
        run: python -m pip install .

      - name: Run pyscipopt tests
        run: |
          py.test

  Windows-test:
    env:
      SCIPOPTDIR: C:\scipoptdir
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare python environment
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel cython networkx pytest-cov

      - name: Install PySCIPOpt
        shell: powershell
        run: |
          $Env:SCIPOPTDIR = "${{ env.SCIPOPTDIR }}"
          python -m pip install .

      - name: Run pyscipopt tests
        shell: powershell
        run: |
          py.test

  MacOS-test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies (SCIPOptSuite)
        id: cache-scip
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/scipoptsuite
            ~/Library/Caches/Homebrew/tbb--*
              /usr/local/opt/tbb*
            ~/Library/Caches/Homebrew/downloads/*--tbb-*
            ~/Library/Caches/Homebrew/boost--*
              /usr/local/opt/boost*
            ~/Library/Caches/Homebrew/downloads/*--boost-*
          key: ${{ runner.os }}-scipopt-${{ env.version }}-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-scipopt-${{ env.version }}-

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare python environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel cython networkx pytest-cov pytest

      - name: Install PySCIPOpt
        run: |
          export SCIPOPTDIR=${{ runner.workspace }}/scipoptsuite/
          export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${{ runner.workspace }}/scipoptsuite/lib
          python -m pip install .

#      - name: Run pyscipopt tests
#        run: |
#          export SCIPOPTDIR=${{ runner.workspace }}/scipoptsuite/
#          export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${{ runner.workspace }}/scipoptsuite/lib
#          py.test

  ### if you need valgrind on mac, you can install it via
  # brew tap LouisBrunner/valgrind
  # brew install --HEAD LouisBrunner/valgrind/valgrind

